# Generated by Django 2.1.8 on 2019-04-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Usuario',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
