# Generated by Django 2.1.8 on 2019-04-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_provedor', models.CharField(blank=True, max_length=50, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=150, null=True)),
                ('valor_pagina', models.FloatField(blank=True, null=True)),
                ('valor_releaser', models.FloatField(blank=True, null=True)),
                ('valor_policy', models.FloatField(blank=True, null=True)),
                ('valor_tracking', models.FloatField(blank=True, null=True)),
                ('franquia', models.IntegerField(blank=True, null=True)),
                ('faturamento_minimo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parceiro',
                'managed': False,
            },
        ),
    ]
