# Generated by Django 2.1.8 on 2019-04-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descritivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoDados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_banco', models.CharField(blank=True, max_length=50, null=True)),
                ('volume_paginas', models.IntegerField(blank=True, null=True)),
                ('qtde_releaser', models.IntegerField(blank=True, null=True)),
                ('policy', models.CharField(blank=True, max_length=3, null=True)),
                ('charge_back', models.CharField(blank=True, max_length=3, null=True)),
                ('tracking', models.CharField(blank=True, max_length=3, null=True)),
                ('isento', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'banco_dados',
                'managed': False,
            },
        ),
    ]
